services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]
  api:
    build:
      context: .          # <- este ponto tem que conter o main.py
      dockerfile: Dockerfile
    env_file: .env
    depends_on: [db]
    ports:
      - "8000:8000"
      - "5010:5010"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
volumes:
  dbdata:
