networks:
  proxy:
    external: true
  telemetry:
    driver: bridge

volumes:
  dbdata:

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
      TZ: America/Belem
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [telemetry]
    restart: unless-stopped

  api:
    image: sua-imagem/telemetry-api:latest   # ou build: .
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file: .env
    depends_on: [db]
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","8000","--proxy-headers","--forwarded-allow-ips","*"]
    # Sem publicar portas no host: o NPM acessa via rede "proxy"
    expose:
      - "8000"   # HTTP interno
      - "5010"   # TCP TRV interno
    networks:
      - telemetry
      - proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5